### PR TITLE
Countries dropdown

### PR DESCRIPTION
**Pull request by jurezila**

### CODE REVIEW

**Review by samo4 — CHANGES_REQUESTED** [review]
country missing $t
<br>?
label structure is IMHO not good for CSS

**Review by samo4 — COMMENTED** [review]
are you sure that this is by value? `code.value = props.countryCode`

**Comment by jurezila** [comment]
should be.. it is a ref..

**Review by samo4 — CHANGES_REQUESTED** [review]
while we're at it..

countryChanged should be fired when you change country.

ctry could be as well country?

id will not work correctly if you have multiple instances of the component

**Comment by samo4** [comment]
`props: ['countryCode']` 

`props: { countryCode: String }`?

**Pull request merged**
